"""Remove website specialties rating from Hospital

Revision ID: a4e507688538
Revises: e0fb9b4655f3
Create Date: 2025-10-11 13:37:45.252257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e507688538'
down_revision = 'e0fb9b4655f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('specialties')
        batch_op.drop_column('website')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('4.5'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specialties', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
